import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import trimesh

# --- CONFIGURATION ---
# Use the dataset generated by the OPTIMIZATION script (not the Canonical one)
DATA_DIR = "MN40_Surface_Voxels" 
CSV_PATH = "MN40_Vector_Labels.csv"
GRID_SIZE = 64

def rotation_matrix_from_vectors(vec1, vec2):
    """ Find the rotation matrix that aligns vec1 to vec2 """
    a, b = (vec1 / np.linalg.norm(vec1)), (vec2 / np.linalg.norm(vec2))
    v = np.cross(a, b)
    c = np.dot(a, b)
    s = np.linalg.norm(v)
    
    if s == 0: # Vectors are already aligned or opposite
        return np.eye(3)
        
    kmat = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])
    rotation_matrix = np.eye(3) + kmat + kmat.dot(kmat) * ((1 - c) / (s ** 2))
    return rotation_matrix

def plot_voxel(ax, voxel_grid, title):
    coords = np.argwhere(voxel_grid == 1)
    if len(coords) == 0: return
    
    # Swap axes for plotting if necessary to match visual expectation
    # Matplotlib 3D is Z-up usually. 
    x, y, z = coords[:, 0], coords[:, 1], coords[:, 2]
    
    ax.scatter(x, y, z, c='steelblue', s=1, alpha=0.3)
    
    # Draw "Floor" at Z=0 to see if it sits flat
    # We create a wireframe grid at min Z
    min_z = np.min(z)
    xx, yy = np.meshgrid(np.linspace(0, 64, 5), np.linspace(0, 64, 5))
    ax.plot_wireframe(xx, yy, np.full_like(xx, min_z), color='gray', alpha=0.2)

    ax.set_xlim([0, 64]); ax.set_ylim([0, 64]); ax.set_zlim([0, 64])
    ax.set_title(title, fontsize=9)
    ax.view_init(elev=10, azim=45) # View from slightly above

def verify_optimization_logic():
    if not os.path.exists(CSV_PATH):
        print("Error: CSV not found.")
        return

    df = pd.read_csv(CSV_PATH)
    
    # Pick 3 random samples
    samples = df.sample(3)
    
    fig = plt.figure(figsize=(12, 12))
    
    for i, (idx, row) in enumerate(samples.iterrows()):
        # 1. Load Data
        voxel_path = os.path.join(DATA_DIR, row['voxel_id'] + '.npy')
        if not os.path.exists(voxel_path): continue
        
        voxel = np.load(voxel_path)
        vector = np.array([row['v_x'], row['v_y'], row['v_z']])
        
        # 2. Plot Original (Tumbling)
        ax1 = fig.add_subplot(3, 2, i*2 + 1, projection='3d')
        # Draw the vector on the original
        center = 32
        ax1.quiver(center, center, center, vector[0]*30, vector[1]*30, vector[2]*30, color='red', linewidth=3)
        plot_voxel(ax1, voxel, f"Original Tumble\nID: {row['voxel_id']}")
        
        # 3. ROTATE TO PRINT ORIENTATION
        # We want to rotate the Voxel Grid so that 'vector' points to [0, 0, -1]
        
        # This is tricky with Voxels (interpolation), so we will rotate the POINTS.
        coords = np.argwhere(voxel == 1)
        # Center coords
        coords = coords - 32.0
        
        # Get rotation R that aligns Vector -> Down ([0,0,-1])
        target_down = np.array([0, 0, -1])
        R = rotation_matrix_from_vectors(vector, target_down)
        
        # Apply rotation
        new_coords = np.dot(coords, R.T)
        
        # Shift back to 0-64 range
        new_coords = new_coords + 32.0
        
        # 4. Plot "Simulated Print"
        ax2 = fig.add_subplot(3, 2, i*2 + 2, projection='3d')
        ax2.scatter(new_coords[:,0], new_coords[:,1], new_coords[:,2], c='green', s=1, alpha=0.3)
        
        # Draw the floor
        min_z = np.min(new_coords[:,2])
        xx, yy = np.meshgrid(np.linspace(0, 64, 5), np.linspace(0, 64, 5))
        ax2.plot_wireframe(xx, yy, np.full_like(xx, min_z), color='gray', alpha=0.2)
        
        ax2.set_xlim([0, 64]); ax2.set_ylim([0, 64]); ax2.set_zlim([0, 64])
        ax2.set_title("Simulated Print Orientation\n(Is this stable?)", fontsize=9)
        ax2.view_init(elev=5, azim=45) # View from ground level

    plt.tight_layout()
    plt.savefig('verify_print_orientation.png')
    print("Check 'verify_print_orientation.png'.")

if __name__ == "__main__":
    verify_optimization_logic()